display_name = "PyHOP"
library_name = "hop"
version = "2.0"
author = "Dana S. Nau"
author_email = "http://www.cs.umd.edu/~nau"
license = "Apache License, Version 2.0"
url = "https://github.com/oubiwann/pyhop"
description = "SHOP-like planner written in Python."
long_description = description
requires = []
